#!/usr/bin/env python3
"""Generate immutable metadata for the pinned Prismarine protocol reference."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


FNV_OFFSET = 14695981039346656037
FNV_PRIME = 1099511628211


def fnv1a64(data: bytes) -> int:
    value = FNV_OFFSET
    for byte in data:
        value = ((value ^ byte) * FNV_PRIME) & 0xFFFFFFFFFFFFFFFF
    return value


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--protocol", type=Path, required=True)
    parser.add_argument("--version", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--commit", required=True)
    args = parser.parse_args()

    protocol_bytes = args.protocol.read_bytes()
    version_bytes = args.version.read_bytes()
    protocol = json.loads(protocol_bytes)
    version = json.loads(version_bytes)
    mappings = protocol["types"]["mcpe_packet"][1][0]["type"][1]["mappings"]
    packets = sorted((int(packet_id), name) for packet_id, name in mappings.items())
    if version != {
        "version": 2168,
        "minecraftVersion": "1.26.40",
        "majorVersion": "1.26",
        "releaseType": "release",
    }:
        raise SystemExit("unexpected version.json metadata")
    if len(packets) != 244 or packets[0][0] != 1 or packets[-1][0] != 350:
        raise SystemExit("unexpected protocol packet catalog")

    lines = [
        "#pragma once",
        "",
        "// Generated by tools/generate_protocol_reference.py. Do not edit by hand.",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace dobby::protocol_reference {",
        "",
        "struct Packet {",
        "    std::int32_t id;",
        "    std::string_view name;",
        "};",
        "",
        f"inline constexpr std::string_view kCommit = {cpp_string(args.commit)};",
        f"inline constexpr std::string_view kProtocolSha256 = {cpp_string(hashlib.sha256(protocol_bytes).hexdigest())};",
        f"inline constexpr std::string_view kVersionSha256 = {cpp_string(hashlib.sha256(version_bytes).hexdigest())};",
        f"inline constexpr std::size_t kProtocolSize = {len(protocol_bytes)};",
        f"inline constexpr std::size_t kVersionSize = {len(version_bytes)};",
        f"inline constexpr std::uint64_t kProtocolFnv1a64 = 0x{fnv1a64(protocol_bytes):016x}ULL;",
        f"inline constexpr std::uint64_t kVersionFnv1a64 = 0x{fnv1a64(version_bytes):016x}ULL;",
        f"inline constexpr std::array<Packet, {len(packets)}> kPackets{{{{",
    ]
    lines.extend(f"        Packet{{{packet_id}, {cpp_string(name)}}}," for packet_id, name in packets)
    lines.extend(["}};", "", "} // namespace dobby::protocol_reference", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
